pub const PRODUCT_NAME: &str = "PG_INDEX_IMPORT";
pub const VERSION_MAJOR: i32 = 0;
pub const VERSION_MINOR: i32 = 1;
pub const VERSION_PATCH: i32 = 0;
pub const VERSION_ALIAS: &str = "Salt Lake City";
pub const COPYRIGHT: &str = "Oleg Potapenko";
pub const COPYRIGHT_YEARS: &str = "2026";
pub const LICENSE: &str = "MIT";
pub const LINK: &str = "https://github.com/PotapenkoOleg/pg_index_import";